### ISSUE TITLE
Allow alternative report location

### ISSUE THREAD

**Issue by renatosilva** [jrfonseca/drmingw#10]
The Program Files directory where applications are usually installed normally requires administration privileges for writing the crash report alongside the executable. Can you please add [this simple function](https://hg.pidgin.im/util/drmingw/rev/088532978452) for allowing us to set an alternative location? Thanks.

**Comment by strixcode** [comment]
Please add this feature. I need to patch my copy of DrMinGW now.

**Comment by renatosilva** [comment]
@jrfonseca, is there anything special with this, or a pull request with the above patch will be enough?
