### ISSUE TITLE
Prin Windows version in crash report

### ISSUE THREAD

**Issue by dismine** [jrfonseca/drmingw#16]
Hi,

In addition to issue #13 i wanna know your thoughts about printing Windows version in crash report. It should be not so hard get this info.

**Comment by White-Tiger** [comment]
actually... starting from Win8.1, Microsoft made it impossible to reliably request the OS version... before 8.1, one could use GetVersionEx to receive the OS version, but this stops working with 8.1+ and always returns Windows 8 for any newer OS unless you specify in your app manifest that your app is meant to run with 8.1, 10, etc... but you can't know those GUID beforehand...
So "best" possible way might be to read the version info of any well known OS dll.. as they resemble the OS in some way.. or finding some different "work around"..

Though a feature like this would also help to fix reports ;) Same for App version (which might not always work), Dr.MinGW version (in case the user didn't update it for what ever reason, or your App version cannot be detected) and OS version so one can go straight ahead and start reproducing ;)

**Comment by jrfonseca** [comment]
I pushed a commit that prints the version using `GetVersionEx`, and added a comment to revise this later for Windows 10.  If somebody manages to get this working reliably on Windows 10 feel free to send a patch.
