### ISSUE TITLE
Unnecessary module versions in report

### ISSUE THREAD

**Issue by renatosilva** [jrfonseca/drmingw#21]
The version-info dumping implemented in a36b428 floods the crash report with many unrelated DLLs. It was supposed to not clutter the stack trace, but it clutters the whole report instead. I suggest you to cache the involved modules in `dumpStack` for printing only these.

**Comment by jrfonseca** [comment]
We already dump the Windows version, and already dump DrMinGW versions in the report which are much less relevant.  It makes no sense not to dump all module versions, when they might actually provide useful info (a wrong DLL version might cause a crash, and not appear in the stack trace very easily -- all it takes is returning a wrong result and cause the caller to crash -- and all you see in the stack trace the info about the caller). 

Many other exception handlers dump all modules too.

I can consider swap the order (e.g, put modules version first, stack back trace last) if everybody thinks that would be better.

But omit restrict module versions seems going backwards to me.

**Comment by strixcode** [comment]
Why don't make it a runtime option (on/off) like log file location?

**Comment by jrfonseca** [comment]
I don't oppose the idea of adding runtime options to exchndl.  But I still believe this is a good behavior.
