### ISSUE TITLE
unable to execute sample with mingw 64bit built binaries

### ISSUE THREAD

**Issue by kreuzberger** [jrfonseca/drmingw#22]
i am testing the project with mingw64.
i can compile everything out of the box with mingw64 release and also with mingw32 release.

i try to test the build on mingw32-build.
sample.rpt is created, a assertion message box is shown.

i try to test the build on mingw64-build
sample.rpt is NOT created, a assertion message box is shown.

adding some fprintf(stderr, ),
it seems the registered exception function seems not to be called on mingw64.
any hints welcome :-)

**Comment by kreuzberger** [comment]
the tests i runned with ctest all passed for the 64bit builds
But as a hint, seems not to like pyhton3 (got errors with catchsegv test on python3

**Comment by jrfonseca** [comment]
> it seems the registered exception function seems not to be called on mingw64.

No clue.  It works fine for me.

What MinGW version are you using?

> But as a hint, seems not to like pyhton3 (got errors with catchsegv test on python3

I don't see how that happened.  `tests/CMakeLists.txt` explicitly searches and uses Python version 2.

**Comment by kreuzberger** [comment]
gcc (rev5, Built by MinGW-W64 project) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.

**Comment by kreuzberger** [comment]
This is the python 3 version:
Found PythonInterp: c:/Anaconda/python.exe (found suitable version "3.4.3", minimum required is "2.7") 
And this the first error:
6: Test timeout computed to be: 9.99988e+006
6:   File "/drmingw/tests/apps/test.py", line 60
6:     def test((catchsegvExe, testExe, testSrc)):

**Comment by kreuzberger** [comment]
seems it depends on the mingw version i am using.
The version i use is 4.8.1 with sjlj exception handling. in my tests (unittest) this worked fine.
But if i have any kind of QtApplication or with you sample it doesnt work
so i downloaded and install mingw64 with SEH exception handling and it worked fine.

**Comment by jrfonseca** [comment]
I suspect that some other module is overriding ExcHndl's `SetUnhandledExceptionFilter`.

I don't know who/how/why is doing that.  But maybe initializing the ExcHndl later will avoid this.

**Comment by kreuzberger** [comment]
Does not help. Only the switch to the SEH mingw release did help. so i close it now due to this
