### ISSUE TITLE
Memory leaks in dwarf_pe.cpp

### ISSUE THREAD

**Issue by ssbssa** [jrfonseca/drmingw#27]
[UnmapViewOfFile()](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366882.aspx) is needed in label **no_intf** and dwarf_pe_finish().
And intfc needs to be freed in dwarf_pe_finish() as well (like _free(dbg->de_obj_file);_).

**Comment by jrfonseca** [comment]
Thanks, fixed.

BTW, your https://github.com/ssbssa/heob project looks quite interesting.  You might find some of the code https://github.com/apitrace/apitrace/tree/master/inject useful, as it has lots of workarounds for problems I found over the years.  That said, I think that IAT patching is too brittle, and one of these days I'm going to scratch that code and use [mhook](http://codefromthe70s.org/mhook24.aspx).

**Comment by ssbssa** [comment]
Thanks for the links, mhook looks really interesting.
