### ISSUE TITLE
WinDbg dbghelp.dll from Win10 SDK needs dbgcore.dll to work

### ISSUE THREAD

**Issue by alvinhochun** [jrfonseca/drmingw#37]
I don't know what the deal is, but looks like `dbghelp.dll` imports two symbols from `dbgcore.dll`. I've made the change alvinhochun/drmingw@1d558abc8e4eb93a8ca6e1ed6112efb7412c0b91 to deploy and package it, but I wonder if it is correct at all.

**Comment by jrfonseca** [comment]
It's first time I'm hearing about `dbgcore.dll` too, but indeed https://msdn.microsoft.com/en-us/library/windows/desktop/ms680359(v=vs.85).aspx seems to indicate that some of DbgHelp interfaces do require both DbgHelp.dll and Dbgcore.dl DLLs to work, both being redistributable.

Your change looks good.
