### ISSUE TITLE
DrMinGW V0.8.2 - Doesn't work on Windows 10/64-bit

### ISSUE THREAD

**Issue by DerellLicht** [jrfonseca/drmingw#38]
I'm building my application using MinGW V4.4.1; 32-bit application;
I build with -g debug flag.  
I wanted to use DrMinGW to find out what's going wrong, as I've done so often in the past, 
but your program doesn't trigger at all when my program crashes, for some reason.
I get the dialog for "this program has terminated improperly blah blah blah",
but I only get the Close button, no Debug button.

I ran 'drmingw.exe -i' as admin on this machine, and it said that it installed successfully.

Any idea what is going on, and maybe what could be done about it?

**Comment by DerellLicht** [comment]
Windows info:
Version 1709 (OS Build 16299.611)

Unfortunately, I don't seem to be able to force that program crash any more !! I hate that!!
I'll have to generate some other error to test this out...

**Comment by DerellLicht** [comment]
Okay, I got the error to recur, and your catchsegv program worked beautifully...
Unfortunately, for some reason, I'm not getting map info for the error entries in my program (wgtext.exe)...
I remember discussing this very issue with you several years ago, with Windows 7 64-bit, but I no longer recall what the fix was... I *do* remember that you told me to do *something* that would resolve my program references...

[wgtext.errors.txt](https://github.com/jrfonseca/drmingw/files/2424864/wgtext.errors.txt)

**Comment by jrfonseca** [comment]
I reproed here.

It works if one installs drmingw with `-a` option, that is:

    drmingw -i -a

That is, it seems the non-auto mode (that is the WER dialog saying app crash and whether to debug) doesn't work...
