### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [jrfonseca/drmingw#52]
The README file in this repo has some bad links - [404:NotFound]

Status code [404:NotFound] - Link: https://bitbucket.org/edd/dbg/wiki/Home
Status code [404:NotFound] - Link: http://www.microsoft.com/msj/0197/exception/exception.htm
Status code [404:NotFound] - Link: http://www.microsoft.com/msj/0497/hood/hood0497.htm
Status code [404:NotFound] - Link: http://www.microsoft.com/msj/0597/hood0597.htm
Status code [404:NotFound] - Link: http://www.microsoft.com/msj/0898/bugslayer0898.htm

These old links are re-directing:
Status code [403:Forbidden] - Link: http://msdn.microsoft.com/en-us/library/windows/desktop/ms679294.aspx
Status code [403:Forbidden] - Link: http://msdn.microsoft.com/en-us/library/windows/desktop/bb204634.aspx
Status code [403:Forbidden] - Link: http://msdn.microsoft.com/en-us/library/windows/hardware/ff558829.aspx
Status code [403:Forbidden] - Link: https://msdn.microsoft.com/en-us/library/ms809754.aspx

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by jrfonseca** [comment]
Thanks. Neat!
