### ISSUE TITLE
0.4.4 is the last one to support Windows 2000

### ISSUE THREAD

**Issue by White-Tiger** [jrfonseca/drmingw#9]
It seems like v0.4.4 is the very last one that still supports Windows 2000
Could you add a note somewhere? Especially as a release note to https://github.com/jrfonseca/drmingw/releases/tag/0.4.4

**Comment by jrfonseca** [comment]
I don't recall what changed afterwards that broke Windows 2000.  Anyway I'm not interested in maintaining Windows 2000 compatibility (keeping XP support is already hard enough). So I've updated the release notes as you suggested. Thanks

**Comment by White-Tiger** [comment]
Just a follow up on what changed after 0.4.4:

* 0.5.1 started to require AddVectoredExceptionHandler in KERNEL32.dll
* 0.6.5 onwards also requires a newer dbghelp.dll (W2k got dbghelp 5.0)
As they started to make use of these functions:
 * EnumDirTree (since dbghelp 6.2)
 * EnumDirTreeW (since dbghelp 6.3)
 * EnumerateLoadedModulesW64 (since dbghelp 6.6)
 * SymSetScopeFromAddr (since dbghelp 6.8 which doesn't run on W2k)
